class OffersListModel {
  String id, companyId, branchId, couponType, companyDiscount, comission, customerDiscount, discountDetail,
      description, arbDescription, startDate, endDate, timing, onlineLink, playstoreLink, iosLink, huawaiLink,
      priority, priorityStart, priorityEnd, hMobileNo, hWhatsappNo, hInstagram, hEmail, hLocation,
      hArabLocation, hImage, mall, mallName, mallNameArabic, custmise, offerNameCust, offerNameCustArabic,
      discountdisplay, companyName, companyArbName, displayName, displayArbName, companylogo, viewCount,
      category, discountEnDetail, discountArbDetail, userFav, customerId, remainingday, remaininghours,
      remainingminutes, isFav;

  OffersListModel(
      this.id,
      this.companyId,
      this.branchId,
      this.couponType,
      this.companyDiscount,
      this.comission,
      this.customerDiscount,
      this.discountDetail,
      this.description,
      this.arbDescription,
      this.startDate,
      this.endDate,
      this.timing,
      this.onlineLink,
      this.playstoreLink,
      this.iosLink,
      this.huawaiLink,
      this.priority,
      this.priorityStart,
      this.priorityEnd,
      this.hMobileNo,
      this.hWhatsappNo,
      this.hInstagram,
      this.hEmail,
      this.hLocation,
      this.hArabLocation,
      this.hImage,
      this.mall,
      this.mallName,
      this.mallNameArabic,
      this.custmise,
      this.offerNameCust,
      this.offerNameCustArabic,
      this.discountdisplay,
      this.companyName,
      this.companyArbName,
      this.displayName,
      this.displayArbName,
      this.companylogo,
      this.viewCount,
      this.category,
      this.discountEnDetail,
      this.discountArbDetail,
      this.userFav,
      this.customerId,
      this.remainingday,
      this.remaininghours,
      this.remainingminutes,
      this.isFav);
}